_array_structures:
  content_blocks:
    style: modal
    values:
      - label: Hero
        image: /static/image/dashboard.png
        value:
          _block_type: content/hero
          title:
          subtitle:
          cta_link:
          cta_text:
          image:
          image_alt:
      - label: Screenshot
        image: /static/image/dashboard.png
        value:
          _block_type: content/screenshot
          content_markdown:
          image:
          image_alt:
      - label: Quote
        image: /static/image/dashboard.png
        value:
          _block_type: content/quote
          image:
          image_alt:
          content_markdown:
          author:
      - label: CTA
        image: /static/image/dashboard.png
        value:
          _block_type: content/cta
          heading_markdown:
          cta_link:
          cta_text: