_array_structures:
  content_blocks:
    style: modal
    values:
      - label: Hero
        icon: vertical_align_top
        tags:
          - Image
          - Heading
        value:
          _block_type: content/hero
          title:
          subtitle:
          cta_link:
          cta_text:
          image:
          image_alt:
      - label: Screenshot
        icon: vertical_split
        tags:
          - Image
          - Markdown
        value:
          _block_type: content/screenshot
          content_markdown:
          image:
          image_alt:
      - label: Quote
        icon: format_quote
        tags:
          - Markdown
        value:
          _block_type: content/quote
          image:
          image_alt:
          content_markdown:
          author:
      - label: CTA
        icon: smart_button
        tags:
          - Info
        value:
          _block_type: content/cta
          heading_markdown:
          cta_link:
          cta_text: