baseURL = "https://strawberry-bat.cloudvent.net/"
languageCode = "en-us"
title = "Hydra Template"

Paginate = 10
PaginatePath = "/"

[taxonomies]
  category = "categories"

[permalinks]
  posts = ":section/:year/:month/:day/:title/"

[markup.goldmark.renderer]
unsafe = true

[params._options.type]
hidden = true

[params._options.full_width]
hidden = true


[params._array_structures.content_blocks]
style = "modal"
[[params._array_structures.content_blocks.values]]
label = "Callout"
icon = "emoji_objects"
description = "Informational callout sitting alongside content"
tags = ["Supporting", "Markdown", "Content"]
[params._array_structures.content_blocks.values.value]
callout_style = "info"
content = "This is an informational callout"

[[params._array_structures.content_blocks.values]]
label = "Hero"
icon = "vertical_align_top"
description = "A primary page hero block"
tags = ["Hero", "Markdown"]
[params._array_structures.content_blocks.values.value]
image = "/dashboard.png"
image_alt_text = "The dashboard of the Hydra CMS"
title = "Page Hero Title"